---
inherit_gem:
  rubocop-rickselby:
    - config/default.yml # generic Ruby rules and cops
    - config/capybara.yml # capybara-specific rules and cops
    - config/factory_bot.yml # factory_bot-specific rules and cops
    - config/rails.yml # Rails-specific rules and cops
    - config/rspec.yml # RSpec-specific rules and cops
    - config/rspec_rails.yml # RSpec/rails-specific rules and cops
