# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/guides" do
  # This should return the minimal set of attributes required to create a valid
  # Guide. As you add validations to Guide, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Guide.create! valid_attributes
      get guides_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      guide = Guide.create! valid_attributes
      get guide_url(guide)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_guide_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      guide = Guide.create! valid_attributes
      get edit_guide_url(guide)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Guide" do
        expect do
          post guides_url, params: { guide: valid_attributes }
        end.to change(Guide, :count).by(1)
      end

      it "redirects to the created guide" do
        post guides_url, params: { guide: valid_attributes }
        expect(response).to redirect_to(guide_url(Guide.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Guide" do
        expect do
          post guides_url, params: { guide: invalid_attributes }
        end.not_to change(Guide, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post guides_url, params: { guide: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested guide" do
        guide = Guide.create! valid_attributes
        patch guide_url(guide), params: { guide: new_attributes }
        guide.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the guide" do
        guide = Guide.create! valid_attributes
        patch guide_url(guide), params: { guide: new_attributes }
        guide.reload
        expect(response).to redirect_to(guide_url(guide))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        guide = Guide.create! valid_attributes
        patch guide_url(guide), params: { guide: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested guide" do
      guide = Guide.create! valid_attributes
      expect do
        delete guide_url(guide)
      end.to change(Guide, :count).by(-1)
    end

    it "redirects to the guides list" do
      guide = Guide.create! valid_attributes
      delete guide_url(guide)
      expect(response).to redirect_to(guides_url)
    end
  end
end
