version: '2.4'

services:
  app:
    image: $CONTAINER_PROD
    restart: always
    container_name: ciclos-major-rails-app
    environment:
      VIRTUAL_HOST: rails.ciclosmajor.com
      LETSENCRYPT_HOST: rails.ciclosmajor.com
      LETSENCRYPT_EMAIL:
      CONTAINER_ROLE: app
      RACK_ENV: production
      RAILS_MASTER_KEY:

networks:
  default:
    name: ciclos-major-rails
