# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: test
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: ciclos-major-dev

test:
  <<: *default
  database: ciclos-major-test

production:
  <<: *default
  host: postgres
  database: <%= ENV.fetch("POSTGRES_DB") { "" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
